#
#   Author: Rohith
#   Date: 2015-07-20 16:46:40 +0100 (Mon, 20 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-service
spec:
  replicas: 1
  selector:
    name: test-service
  template:
    metadata:
      labels:
        name: test-service
      anontations:
        metrics: |
        - name: collectd
          port: 8001
        - name: statsd
          port: 8002
    spec:
      containers:
      - name: test-service
        image: fedora/apache
        ports:
        - containerPort: 80
      - name: collectd-exporter
        image: prom/collectd-exporter
        ports:
        - containerPort: 8001
      - name: statsd-exporter
        image: prom/statsd-exporter
        ports:
        - containerPort: 8002
